#!/usr/bin/env python

import argparse

def display_help():
    print(f'Hello, do you want help?')

def commit(parser):
    print("Performing a commit option.")
    args, remaining_args = parser.parse_known_args()
    print(remaining_args)

def farewell(name):
    print(f'Goodbye, {name}!')

def ask_chatgpt(ask):
    print(f'ask this question {ask}.')

def main():

    option_list = [
        'chatgpt',
        'search',
        'farewell',
        'commit'
    ]

    option_list_help_message = f'Specify an option {option_list}'

    parser = argparse.ArgumentParser(description='John\'s Custom CLI')

    parser.add_argument('--m', help='Add commit message.')
    parser.add_argument('option', choices=option_list, help=f'Specify option {option_list}')

    args = parser.parse_args()

    if args.option == 'commit':
        if args.m == None:
            print("A message (--m) is required for commits.")
        else:
            commit(parser)

    elif args.option == 'farewell':
        print("Performing a farewell option.")


if __name__ == '__main__':
    try:
        main()
    except SystemExit:
        # Define your custom error message
        custom_error_message = "Your custom error message here."
        print(custom_error_message)
